baseURL = 'https://thinkingbits.io/'
languageCode = 'en-us'
title = 'Thinking Bits'
theme = 'tlzr'

[caches]
[caches.images]
dir = ':cacheDir/images'

[[menus.nav]]
name = 'Home'
url = '/'
weight = 1

[[menus.nav]]
identifier = 'about'
name = 'About'
url = '/about'
weight = 2

[[menus.navdropdown]]
name = 'Posts'
url = '/posts'
weight = 20

[[menus.navdropdown]]
name = 'Tags'
url = '/tags'
weight = 30

[[menus.navdropdown]]
name = 'Paper Review'
url = '/paper-review'
weight = 40

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[params]
dateFormat = "2 January 2006"
intro = "This site is a place for me to put some assorted thoughts and self-references. A primary goal is to work through the content from my grad degree, developing my own explanations, diving deeper into subjects I am less familiar with, and starting to develop the muscle of working through academic papers."
